name: Publish Project to Website

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm ci 
        
      - name: Build Site
        env:
          REACT_APP_TENANT_API: https://cairnsgames.co.za/php/tenant/
          REACT_APP_AUTH_API: https://cairnsgames.co.za/php/auth/
          REACT_APP_SETTINGS_API: https://cairnsgames.co.za/php/settings/api.php/
          REACT_APP_CONTENT_API: https://cairnsgames.co.za/php/content/
          REACT_APP_FILES: https://cairnsgames.co.za/files/
          REACT_APP_PAYWEB3_API: http://cairnsgames.co.za/php/payweb3/
          NOTIELF_API: ./php/
        run: npm run build        

      - name: Deploy Site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ vars.SERVER_DIR }}

  deploy_php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4           

      - name: Deploy php
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./php/
          server-dir: ${{ vars.PHP_DIR }}
